### ISSUE TITLE
Excel doesnt like the proj.xll in releases

### ISSUE THREAD

**Issue by scaddenp** [jbuonagurio/proj.xll#1]
I grabbed the proj.xll from releases but when I load it into Excel, I get message
The file format and extension of 'proj.xll' dont match. The file could be corrupted or unsafe. 
Trying to load into Excel 2016 MSO 32 bit. (Office 365)

**Comment by jbuonagurio** [comment]
I'm using Excel version 1902 (Build 11328.20230) for Office 365 and it seems to work on my end. Could be that I didn't statically link the MSVC runtime. I'll look at the DLL and get a new version out in the next day or two.

I'll look into updating PROJ as well, but the new versions depend on an external SQLite database which could complicate deployment. I may be able to embed it as a resource if the PROJ API supports it...

Thanks for the bug report. I wasn't sure anyone was using this!

**Comment by scaddenp** [comment]
Which runtime is it compiled for. Might indeed be the problem.

**Comment by scaddenp** [comment]
As a possible way to sort out the issue, I tried building it. Sadly, only have VS Studio 2010. It doesnt compile there. (unknown switches /sdl /Zc:inline and things went bad from there...

**Comment by jbuonagurio** [comment]
Looks like I didn't create a full static build previously. I uploaded a new release, fully statically linked to PROJ 4.9.3 and the XLL framework (only dependencies are on KERNEL32.dll and XLCall32.dll).

I'll work on integrating PROJ 6.2.0 and possibly migrating to C++ in the next week or two. The new PROJ [transformation pipelines](https://proj.org/usage/transformation.html#transformation-pipelines) are really convenient.

**Comment by scaddenp** [comment]
YES! That version works.

**Comment by MagitekKnight** [comment]
Hi! Your project looks really handy, but I run into the same problem as scaddenp! I'm trying to import the .xll-files into Excel 2010 (version 13328.20356 or more specifically: 365MSO, 16.0.13328.20350, 64 bit). It doesn't say anything special when I first add the add-in, but if I close and open Excel again then I get the same error message as described above.

Could it be the 64 bit-detail that's the issue, or is there such a large difference between the Excel versions? I have tried both existing releases, but I get the same behaviour for both of them.

Thanks for any assistance!
